language: node_js
cache:
  directories:
  - "~/.npm"
  - node_modules
node_js:
- 8
branches:
  only:
  - master
env:
  global:
    # CODACY_PROJECT_TOKEN
    secure: zUXDlXwriw51SYQYYXydRyfUhgSlmGzo9Xud9h5scHTWM0e6OrfB/LXzlt04HW2IXGkwDgOF18FR693Ikhgos5aA2OAfHNtK6HrZ40RbGRURvziuwpHDmLfgY6Sksg5StxrHv7p0LwPcV/zDDPNg3j3n7JTVHPD5bOJfmvUlIDGaHKvzn7VTmPCHE7gMzx5fGvjqSnTC7qjSafo50qI2rCdbLTFM2DOToLkiokTsqLCCZ25yf+QOwSMCkmnqvK1VaAXefzj2oreNXYegxzWS+P8ldkx9NJhOwnlSeFbGuoFi2sVsI87/9+FnpeodEBitDI6OYXI1shb3THigfmEwna3V62fb6qsTTKrPwumdVg6O9nxkp+c2rtEX527pEXqwZXyonNyXgaKT7FHI6svVUYyQbY0z45BkSxkrZnTbhPmQywpdwyCFjrLqo3FywxrJKV6XlGU2wMljG5TOewWSS2FcTbvm1Q3GbZJCoewW7XMQJMCasqserjAERxl40MiXstoi5yvA2mPMQ5Ihbt3l8aVbJoeJLrnrbieq7MH14JtEitUAnAp+0VkLGakEqxQ6zxmsMlLQV/Gtz0mPOTggxD5i5+rtTsx6qg9S/nWdezCrLmePcFl6MPx+yBxdT4192naF36dP8uURBg7u20NoqTbb+Odx5L0H3ghcOf1z3j0=
install: npm i
script:
- npm run bootstrap
- set -e
- npm run lint
- npm run test:ci
after_success:
- npm run build
