language: node_js
cache:
  directories:
  - "~/.npm"
  - node_modules
node_js:
- 8
branches:
  only:
  - master
env:
  global:
    # CODE CLIMATE
    - CC_TEST_REPORTER_ID=c7892a83184e24f1283acb42fbad83560ea94719318c3d94d38d92681f71261e
jobs:
  include:
    # JS lint and unit tests
    - stage: Lint & unit tests
      install: yarn
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        # Lint our code
        - npm run lint
        # Test our code
        - npm run test:ci
      after_script:
        # Send report to Code Climate
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ./coverage/lcov.info
    # Integration tests
    - stage: Integration tests
      install: yarn
      before_script:
        # Build final bundles
        - npm run build
        # Start integration server
        - npm run serve:dist &
      script:
        - npm run test:integration
        # This one feels hacky, but does the job of killing the server
        - pkill node
