language: node_js
cache:
  directories:
  - "~/.npm"
  - node_modules
node_js:
- 8
branches:
  only:
  - master
env:
  global:
    # CODACY_PROJECT_TOKEN
    secure: 2siSggm5+P/hAW+VqXKL99jP+fMWODBAYHOo3Eqt2VcO1DheSCsEcSvt6CnYTEmYDPw+o2TfXNyAVpnkeBtAWe/l0g8j19wPhsZhG6PG+34V+YZ0rnt+nC5+TfMHFw86/EBAsynOZ0fRZWrzJx1wLZpV0bpPtgHwWZhp6I7rkMRX5IHod3zh/DavUIm7i+0aca++YWl6kh2jenSAyNYT74zXcjnL8MyI6M94MhTHkaIzm2f2q19igJEmHnIlAsDfPUsgOWldWCDdE2XnKZqFpQLLw2C+7BkiqigX3cTYW/m8lCeiHLhRPXkwy/vz0SARTxwnc4cAfpPqqC92WYrSizYwpae8quoZUcpzBD2pjbO/Isjmh/wqv2pXNqt2/GHeM0wr6mHYDhcH+XGg/ek5eOAJVXClGWYXYM2H11snM4wsagQAwrV752BHY0UP6PdRzUjxfCmcBa/PoRjT2RbODZ9RzKOJuPt3BWuVye21npoK52GK3w8RoPWr1CFjnSLChBaZXip5c0l/VYmYWwvCXuRwO0ZC5ai0bLvJleyOdvM3liHlbH4wIMHQeNj/KNRByaedUENSTNH2At/zvB+2XvJOfrS3vbgeZNZOypXLMDdd2fn+bXWzbvZej0nC4id5A+GWXCbLmHsWCg4ja1lXWyvhoQ1+VoSF1gAP8UM3DZQ=
install: npm i
script:
- npm run bootstrap
- set -e
- npm run lint
- npm run test:ci
after_success:
- npm run build
