language: node_js
cache:
  directories:
  - "~/.npm"
  - node_modules
node_js:
- 8
branches:
  only:
  - master
env:
  global:
    # CODACY_PROJECT_TOKEN
    - secure: zUXDlXwriw51SYQYYXydRyfUhgSlmGzo9Xud9h5scHTWM0e6OrfB/LXzlt04HW2IXGkwDgOF18FR693Ikhgos5aA2OAfHNtK6HrZ40RbGRURvziuwpHDmLfgY6Sksg5StxrHv7p0LwPcV/zDDPNg3j3n7JTVHPD5bOJfmvUlIDGaHKvzn7VTmPCHE7gMzx5fGvjqSnTC7qjSafo50qI2rCdbLTFM2DOToLkiokTsqLCCZ25yf+QOwSMCkmnqvK1VaAXefzj2oreNXYegxzWS+P8ldkx9NJhOwnlSeFbGuoFi2sVsI87/9+FnpeodEBitDI6OYXI1shb3THigfmEwna3V62fb6qsTTKrPwumdVg6O9nxkp+c2rtEX527pEXqwZXyonNyXgaKT7FHI6svVUYyQbY0z45BkSxkrZnTbhPmQywpdwyCFjrLqo3FywxrJKV6XlGU2wMljG5TOewWSS2FcTbvm1Q3GbZJCoewW7XMQJMCasqserjAERxl40MiXstoi5yvA2mPMQ5Ihbt3l8aVbJoeJLrnrbieq7MH14JtEitUAnAp+0VkLGakEqxQ6zxmsMlLQV/Gtz0mPOTggxD5i5+rtTsx6qg9S/nWdezCrLmePcFl6MPx+yBxdT4192naF36dP8uURBg7u20NoqTbb+Odx5L0H3ghcOf1z3j0=
    # NPM_TOKEN
    - secure: s+n+egOnOm5m8g17CHNiCPm+nODq5PjF0EuRKstkUjVR11895FVrvQJglMfPaG66k0tCtSp/uc3ZMMiS+lArI/H8/FRKgbYCxiXFuVthRhSuDnZfca2Uet8xdqatP4RfqGYHOBhXY86/ININU7+ubLp7BvFTY5cGWHLhmhXAkqNWa1WVFLTjgWLOOeW1PVALz2FvSo5zQ9dv5rTIrjwdDpWtdTmvoEj2BcYPFniqxPywkk1NsV7Jy+4uiIoxcMoPiyZDFX7k7CUjnW/HeL0DxFzYy1+dk+rFXkmg/lzjMfATjFsDMSLbCVonr+NOwwnok0HhJuW+jEIEdvhLLWSy7kfnubYbEbYZoZ11VflLHrYGp7mgCszR5eVKY9SU6R8+HeLX34FXQP6+MuEddQvgxJq2CAfVJyYbUmYK87nqroQX8/9b2xnzb67L8C0TVtosdg/Sp+C2wVC+F2gNogfLDC3FEGp05dy3TaqDJBkDsHgTR8/Zm+iowVp7jVDsY9ea2M3gR0WJQY37bKKv0xRhIQ6kLLB4MiFkxFrIRVcHOGU1xQOhGjVaslI6Ex5pyr+h14BpUVb6hcTLYuJB6QH6UwS5v1ncQLyhlQGJrM3S3kQ+pFhNHGi5V2GhYoDVjAXXAx4AhRP71C9GXC0BBXWShEF+iLioNWslxnkSbV0HYD8=
install: yarn
script: scripts/travis/script.sh
after_success: scripts/travis/after_success.sh
